import './styles.css';
const lessons=[['intro','Einleitung','KI in der Kommunikation'],['principles','Lektion 1','Prinzipien'],['transparency','Lektion 2','Transparenz'],['quality','Lektion 3','Freigabe & Qualitätssicherung'],['usecases','Lektion 4','Usecases entlang der Komm-Journey'],['links','Lektion 5','Link-Liste']];
const principles=['Primat der menschlichen Absenderschaft|Publizierte Inhalte bleiben in menschlicher Verantwortung.','Glaubwürdigkeit und Reputation|Fakten, Werte und Reputation werden aktiv geschützt.','Wahrung der städtischen Identität|Sprach- und Gestaltungsvorgaben bleiben verbindlich.','Rechte Dritter respektieren|Urheber-, Nutzungs- und Persönlichkeitsrechte beachten.','Transparenz|KI-Einsatz gemäss Regelung offenlegen oder kennzeichnen.'];
const usecases=[['Auftrag & Rahmen klären','Briefing strukturieren','Lücken, Risiken und offene Fragen sichtbar machen.','Ziel, Botschaft, Zuständigkeit und KI-Eignung entscheiden.'],['Recherche','Themen-, Quellen- und Argumentelandkarte','Öffentliche Quellen clustern und Gegenargumente identifizieren.','Quellenqualität, Fakten und Sensibilitäten prüfen.'],['Konzeption & Ideenfindung','Kommunikationsansätze entwickeln','Botschaften, Kanäle und Dramaturgien variieren.','Strategische Passung und städtische Haltung beurteilen.'],['Redaktion / Text','Textentwürfe und Varianten erstellen','Rohtexte, Kürzungen, barriereärmere Formulierungen liefern.','Fakten, Tonalität, Rechte und politische Sensibilität prüfen.'],['Audiovisueller Content','Storyboards und Alt-Texte vorbereiten','Szenenlisten, Visual-Ideen und Stimmungsbeschriebe vorbereiten.','Keine Realbilder ersetzen, KI-Illustrationen kennzeichnen.'],['Publikation & Weboptimierung','Titel, Teaser und Meta-Angaben optimieren','SEO-Beschriebe, Linktexte und Strukturvorschläge erstellen.','Standards, Barrierefreiheit und Transparenz prüfen.'],['Interaktion & Moderation','Antwortentwürfe vorbereiten','FAQ-Antworten, Kommentarcluster und Eskalationshinweise vorbereiten.','Empathie, Rechtslage, Tonalität und heikle Fälle prüfen.'],['Monitoring & Wirkungsanalyse','Rückmeldungen strukturieren','Feedback, Kennzahlen und Medienresonanz clustern.','Datenschutz und Aussagekraft prüfen; keine Auto-Entscheide.']];
const linkList=['STRB 83/2017 Leitlinien zur Regierungs- und Verwaltungskommunikation','STRB 2281/2025 Richtlinie generative KI','Komm-Anwendungsprinzipien für KI','Transparenzregelung / Deklarationsbeispiele','Deepfake-Merkblatt / Eskalationsweg','CD-Manual, Bildwelt und Office-Vorgaben','Sprachvorgaben der Stadt Zürich','SharePoint Komm-KI-Werkzeuge','ZüriA','Capito','Kontakt Kommunikation / Toolverantwortliche','Datenschutz / Informationssicherheit / ISDS'];
let active='intro', tree=0;
function quiz(kind){let q={principles:['Wer trägt Verantwortung für einen publizierten KI-gestützten Inhalt?','Die nutzende Person bzw. zuständige Dienstabteilung im bestehenden Freigabeprozess.','Das KI-System.'],transparency:['Welche Aussage ist korrekt?','KI-generierte Bilder für externe Publikation sind als solche zu kennzeichnen.','Eine interne Notiz reicht immer.'],quality:['Welche Prüfpunkte gehören zur Freigabe?','Fakten, Rechte, Tonalität, Transparenz, Tool- und Datennutzung sowie Freigabeweg.','Nur Sprachglätte und Promptqualität.']}[kind];return `<div class="quiz"><b>Lernkontrolle</b><p>${q[0]}</p><button data-ok>${q[1]}</button><button>${q[2]}</button><p class="feedback" hidden>✓ Richtig. KI unterstützt — Verantwortung, Prüfung und Freigabe bleiben menschlich und organisatorisch verankert.</p></div>`}
function content(){if(active==='intro')return `<div class="grid"><article class="card wide"><h2>Lernziele</h2><p>Nach dem WBT können Teilnehmende KI-Kommunikationsprinzipien anwenden, Transparenz beurteilen, Freigabeprozesse ergänzen, Usecases einordnen und relevante Grundlagen finden.</p></article><article class="card"><h3>Abgrenzung</h3><p>Das WBT ersetzt keine rechtliche Einzelfallprüfung. Bei erhöhtem Risiko gilt der definierte Eskalationsweg.</p></article><article class="card"><h3>Kurslogik</h3><p>Einleitung, drei Lektionen mit Lernkontrolle, Usecase-Journey und Link-Liste.</p></article></div>`;
if(active==='principles')return `<div class="cards">${principles.map((p,i)=>{let [h,t]=p.split('|');return `<article class="principle"><span>${i+1}</span><h3>${h}</h3><p>${t}</p></article>`}).join('')}</div><article class="statement">KI liefert Vorschläge, Varianten und Struktur. Die Kommunikation entscheidet über Wahrheit, Haltung, Tonalität, Rechte, Kontext und Publikation.</article>${quiz('principles')}`;
if(active==='transparency'){let steps=['Extern publiziert oder öffentliche Interaktion?','KI-Beitrag wesentlich für Inhalt, Aussage, Bild oder Interaktion?','Vollständig menschlich geprüft und verantwortet?','Bild, Video, Audio oder automatische Interaktion?','Kennzeichnung, Hinweis oder Nichtverwendung erforderlich?'];return `<div class="decision"><h2>Klickbarer Entscheidbaum</h2><p>${steps[tree]}</p><button data-tree>Ja / weiter prüfen</button><button data-reset>Zurücksetzen</button></div><div class="grid"><article class="card"><h3>Text</h3><p>Keine Deklaration bei vollständiger menschlicher Kontrolle. Deklaration bei automatischer Publikation ohne Kontrolle.</p></article><article class="card"><h3>Bild & Multimedia</h3><p>KI-generierte Bilder kennzeichnen; keine Fotografie realer Gegebenheiten ersetzen; keine Deepfakes.</p></article></div>${quiz('transparency')}`}
if(active==='quality')return `<div class="checklist">${['Richtigkeit: Fakten, Quellen, Zahlen, Kontext, Bias','Rechte: Urheber-, Nutzungs- und Persönlichkeitsrechte','Tonalität: Sprachvorgaben, CD/CI und Bildwelt','Transparenz: Kennzeichnung oder Deklaration beurteilt','Toolnutzung: ZüriA bzw. freigegebene Tools nach Vorgaben'].map(x=>`<label><input type="checkbox"> ${x}</label>`).join('')}</div><article class="statement">Der Massstab bleibt nicht der beste Prompt, sondern die publizierbare Qualität.</article>${quiz('quality')}`;
if(active==='usecases')return `<div class="timeline">${usecases.map((u,i)=>`<article><b>UC-${String(i+1).padStart(2,'0')}</b><h3>${u[0]} · ${u[1]}</h3><p><strong>KI-Beitrag:</strong> ${u[2]}</p><p><strong>Menschliche QS:</strong> ${u[3]}</p></article>`).join('')}</div>`;
return `<div class="links">${linkList.map(l=>`<a href="#">🔗 ${l}<span>[Link einsetzen]</span></a>`).join('')}</div><article class="statement"><h2>Abschluss</h2><p>KI kann Kommunikationsarbeit wirksamer machen, wenn sie entlang klarer Prinzipien, transparenter Kennzeichnung und sauberer Freigabe eingesetzt wird.</p><p><strong>Transferfrage:</strong> Welche wiederkehrende Aufgabe könnte im eigenen Arbeitsbereich sinnvoll KI-unterstützt werden?</p></article>`}
function render(){let idx=lessons.findIndex(l=>l[0]===active), progress=Math.round((idx+1)/lessons.length*100);document.querySelector('#app').innerHTML=`<header><div class="brand"><span class="crest">▦</span><span>Stadt Zürich</span></div><button class="menu" data-menu>☰</button></header><div class="shell"><aside>${lessons.map((l,i)=>`<button class="${active===l[0]?'sel':''}" data-nav="${l[0]}"><small>${String(i+1).padStart(2,'0')}</small><span>${l[1]}</span></button>`).join('')}</aside><main><div class="progress"><i style="width:${progress}%"></i></div><section class="hero"><div><p class="eyebrow">Web Based Training · ca. 30 Minuten</p><h1>${lessons[idx][2]}</h1><p>Verantwortungsvoll, transparent und qualitätsgesichert mit KI arbeiten — entlang der Kommunikationsprinzipien der Stadt Zürich.</p></div><div class="heroicon">✦</div></section>${content()}<div class="pager"><button ${idx===0?'disabled':''} data-prev>Zurück</button><button ${idx===lessons.length-1?'disabled':''} data-next>Weiter ›</button></div></main></div>`}
document.addEventListener('click',e=>{let n=e.target.closest('[data-nav]');if(n){active=n.dataset.nav;render()} if(e.target.matches('[data-next]')){let i=lessons.findIndex(l=>l[0]===active);active=lessons[i+1][0];render()} if(e.target.matches('[data-prev]')){let i=lessons.findIndex(l=>l[0]===active);active=lessons[i-1][0];render()} if(e.target.matches('[data-ok]'))e.target.parentElement.querySelector('.feedback').hidden=false; if(e.target.matches('[data-tree]')){tree=Math.min(tree+1,4);render()} if(e.target.matches('[data-reset]')){tree=0;render()} if(e.target.matches('[data-menu]'))document.querySelector('aside').classList.toggle('open')});
render();
